const actionTypes = {

  GET_CHARACTER_REQUESTED: 'GET_CHARACTER_REQUESTED',
  GET_CHARACTER_SUCCEEDED: 'GET_CHARACTER_SUCCEEDED',
  GET_CHARACTER_FAIL: 'GET_CHARACTER_FAIL',

  GET_WIRE_CHARACTER_REQUESTED: 'GET_WIRE_CHARACTER_REQUESTED',
  GET_WIRE_CHARACTER_SUCCEEDED: 'GET_WIRE_CHARACTER_SUCCEEDED',
  GET_WIRE_CHARACTER_FAIL: 'GET_WIRE_CHARACTER_FAIL',

};

export { actionTypes };
